Feature/kanban board
proun95/task-manager pull request #14
Opened 2021-11-21 10:20 UTC by proun95

2021-11-21 19:40 UTC, greybutton requested changes

2021-11-21 19:40 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +const TaskBoard = function () {
почему так написал и еслинт дисейблишь?

2021-11-22 06:24 UTC, proun95 commented on app/javascript/components/TaskBoard/TaskBoard.js
> +const TaskBoard = function () {
Попробовал сделать так:
`const TaskBoard = () => <Board initialBoard={data} disableColumnDrag />;`
Работает, однако на такую строку еслинт выдает ошибку, на изначальный вариант выдает ворнинг, поэтому отключил линтер для этой строки. Делал согласно этому правилу https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md
Перепробовал почти все способы, это единственный, который не вызывает ошибку (только ворнинг).

2021-11-22 07:16 UTC, proun95 commented on app/javascript/components/TaskBoard/TaskBoard.js
> +const TaskBoard = function () {
Даже такой вариант
```
var Component = (props) => {
  return <div />;
};
```
представленный, как вариант корректного кода в документации, выдает ошибку
`Function component is not a function expression (eslintreact/function-component-definition)`

2021-11-22 15:45 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +const TaskBoard = function () {
ок, спасибо. видимо новое правило

2021-11-22 15:45 UTC, greybutton approved these changes

2021-11-22 17:28 UTC, merged