Feature/tasks
proun95/task-manager pull request #15
Opened 2021-11-26 08:36 UTC by proun95

2021-11-29 19:46 UTC, greybutton requested changes

2021-11-29 19:46 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.all.order('created_at DESC').
ордер не задается в контроллере, он через рансак будет ставиться фронтом

2021-11-29 19:46 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +    // changeOpenedTask(null);
setOpenedTaskId?

2021-11-29 19:46 UTC, greybutton commented on package.json
> +    "ramda": "^0.27.1",
не хватает qs

2021-11-29 20:50 UTC, proun95 commented on app/javascript/components/TaskBoard/TaskBoard.js
> +    // changeOpenedTask(null);
Забыл последние изменения залить

2021-11-29 21:04 UTC, proun95 commented on package.json
> +    "ramda": "^0.27.1",
Странно, что на импорт в fetchHelper не ругался на отсутствие библиотеки

2021-11-30 07:07 UTC, greybutton approved these changes

2021-11-30 07:51 UTC, merged