Feature/redux
proun95/task-manager pull request #17
Opened 2021-12-08 16:53 UTC by proun95

2021-12-09 16:59 UTC, greybutton requested changes

2021-12-09 16:59 UTC, greybutton commented on app/javascript/App.js
> +// import MUITheme from 'MUITheme/MUITheme';
тема стоит добавить

2021-12-09 16:59 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +import { changeColumn } from '@asseinfo/react-kanban';
перемешаны импорты, сначала пакеты, потом локальные файлы

2021-12-09 16:59 UTC, greybutton commented on app/javascript/hooks/store/useTasks.js
> +import { states } from 'presenters/TaskPresenter';
это работает? у тебя же STATES называется

2021-12-09 16:59 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +  };
где остальные методы?

2021-12-13 06:05 UTC, proun95 commented on app/javascript/App.js
> +// import MUITheme from 'MUITheme/MUITheme';
Не могу понять, такого пакета не существует, пользовательскую тему мы также не создавали, попробовал добавить, но что конкретно менять по дизайну непонятно

2021-12-13 18:35 UTC, greybutton commented on app/javascript/App.js
> +// import MUITheme from 'MUITheme/MUITheme';
достаточно дефолтную добавить

https://v4.mui.com/customization/theming/
https://v4.mui.com/customization/default-theme/#default-theme

2021-12-15 18:57 UTC, proun95 commented on app/javascript/slices/TasksSlice.js
> +  };
Бьюсь-бьюсь над этим, судя по тексту практики методы эти должны быть в containers/TaskBoard, но, видимо, нет

2021-12-16 06:49 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +  };
использоваться будут в containers/TaskBoard, а основной их код в слайсе

2021-12-22 07:04 UTC, greybutton approved these changes

2021-12-22 07:04 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +  };
это разве не повтор loadAdditionalColumn? 

loadAdditionalColumnSuccess два раза вызовется

2021-12-23 05:41 UTC, merged