add state machine for Task
proun95/task-manager pull request #6
Opened 2021-11-07 13:54 UTC by proun95

2021-11-07 14:23 UTC, moklidia requested changes

2021-11-07 14:23 UTC, moklidia commented on app/models/task.rb
> +    event :ready_for_release do
Пожалуйста поменяй названия событий так, чтобы это было действие - глагол.

2021-11-08 06:57 UTC, moklidia requested changes

2021-11-08 06:57 UTC, moklidia commented on app/models/task.rb
> +    event :arhive do
Опечатка - archive

2021-11-08 06:57 UTC, moklidia commented on app/models/task.rb
> +    event :develop do
Это событие тоже нужно переименовать

2021-11-08 19:25 UTC, greybutton requested changes
проверь рубокоп

2021-11-08 19:25 UTC, greybutton commented on app/models/task.rb
> +      transition :in_code_review => :in_development
посмотри в доке, как можно короче записать

2021-11-08 20:50 UTC, greybutton approved these changes

2021-11-09 05:01 UTC, merged